DIGITAL_OUTPUTS_FROM_CONVEYOR_TO_FANUC = {
    "PD_CONVEYOR_STOPPED": 10,
}

DIGITAL_OUTPUTS_FROM_FANUC_TO_PI = {
    "HEARTBEAT": 23, 
    "ROBOT_IN_POSITION_FOR_CAPTURE": 12,  
    "PART_SEQUENCE_DONE": 13, 
    "ACKNOWLEDGEMENT": 14,   
}

DIGITAL_OUTPUTS_FROM_PI_TO_FANUC = {
    "CAPTURE_DONE": 5,         
    "ERROR_SIGNAL": 23,  
    "RESET_SIGNAL": 24,
    
    "RECIPE_BIT_2": 26,
    "RECIPE_BIT_1": 13,
    "RECIPE_BIT_0": 6,       
}